site_name: Galaxy App API Docs

nav:
  - Home: index.md
  - API Reference: api.md
  - AST Explorer:
      - galaxy/tool/explorer/explorer.py: auto-docs/galaxy_tool_explorer_explorer.md
      - main.py: auto-docs/main.md
      - models/schemas.py: auto-docs/models_schemas.md

plugins:
  - mkdocstrings

theme:
  name: material
